version: "3"

services:
  flask:
    build: ./server
    restart: on-failure
    ports:
      - "5000"
    volumes:
      - ./server/uploads:/usr/src/app/uploads
    networks:
      - proxy-server

  nginx_with_client:
    build: ./client
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./server/uploads:/usr/share/nginx/uploads
    depends_on:
      - flask
    networks:
      - proxy-server

networks:
  proxy-server: